[x,y] = textread('time0.txt','%f %f');
plot(x,y,'r');
hold on;
[x,y] = textread('time1.txt','%f %f');
plot(x,y,'g');
hold on;
[x,y] = textread('time2.txt','%f %f');
plot(x,y,'b');
xlabel('包的等待时间(us)');
ylabel('概率');
legend('队列1','队列2','队列3');
